#Copyright 2024-2026 the original author or authors.
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

FROM eclipse-temurin:17-jdk-jammy as build

WORKDIR /app

# 安装所需的软件
RUN apt update && apt install -y maven git

# (可选)配置Maven国内镜像源，加速构建
# RUN echo '<settings>\
#  <mirrors>\
#    <mirror>\
#      <id>aliyun</id>\
#      <url>https://maven.aliyun.com/repository/public</url>\
#      <mirrorOf>*</mirrorOf>\
#    </mirror>\
#  </mirrors>\
#  <profiles>\
#    <profile>\
#      <id>default</id>\
#      <activation>\
#        <activeByDefault>true</activeByDefault>\
#      </activation>\
#      <properties>\
#        <maven.compiler.source>17</maven.compiler.source>\
#        <maven.compiler.target>17</maven.compiler.target>\
#      </properties>\
#    </profile>\
#  </profiles>\
#</settings>' > aliyun-settings.xml

# 复制本地代码到构建容器
COPY . /app/DataAgent

# 进入项目目录并构建
WORKDIR /app/DataAgent
RUN mvn install -DskipTests -Dspotless.apply.skip=true
#    mvn install -DskipTests -s ../aliyun-settings.xml

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=build /app/DataAgent/data-agent-management/target/spring-ai-alibaba-data-agent-management-1.0.0-SNAPSHOT.jar /app/app.jar

RUN apt update && apt install -y python3

# 创建配置文件目录
RUN mkdir -p /app/config

EXPOSE 8065

# 启动命令，优先使用外部配置文件
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=classpath:application.yml,optional:file:/app/config/application.yml"]
